language: node_js

node_js:
  - "11"
  - "10"
  - "8"

install:
  npm i -g yarn

before_script:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint:fix
  
notifications:
  email:
    on_success: never
    on_failure: always
